specVersion: 1.0.0
name: moonbuilders-demo
version: 0.0.1
runner:
  node:
    name: "@subql/node"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: 'A basic Substrate EVM example project with an event and call handler. Read more
  about this at https://academy.subquery.network/build/substrate-wasm.html. This
  project can be use as a starting point for developing your SubQuery project'
repository: 'https://github.com/subquery/subql-starter.git'
schema:
  file: ./schema.graphql
network:
  # The genesis hash of the network (hash of block 0)
  chainId: "0xfe58ea77779b7abda7da4ec526d14db9b1e9cd40a217c34892af80a9b332b76d"
  # This endpoint must be a public non-pruned archive node
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key
  # You can get them from OnFinality for free https://app.onfinality.io
  # https://documentation.onfinality.io/support/the-enhanced-api-service
  endpoint:
    [
      "wss://moonbeam.api.onfinality.io/public-ws",
      "wss://wss.api.moonbeam.network",
    ]
  dictionary: "https://api.subquery.network/sq/subquery/moonbeam-dictionary"
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 69218
    mapping:
      file: './dist/index.js'
      handlers:
        - handler: collatorJoined
          kind: substrate/EventHandler
          filter:
            module: staking
            method: joinCandidates
        - handler: collatorLeft
          kind: substrate/CallHandler
          filter:
            module: staking
            method: executeLeaveCandidates
  - kind: substrate/Moonbeam
     # This is the datasource for Moonbeam's EVM processor
    startBlock: 3281780
    processor:
      file: ./node_modules/@subql/frontier-evm-processor/dist/bundle.js
      options:
        abi: erc20
        contract: "0x322E86852e492a7Ee17f28a78c663da38FB33bfb" # Mainnet
    assets:
      erc20:
        file: ./erc20.abi.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleErc20Transfer
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Transfer(address indexed from,address indexed to,uint256 value)

